import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@madrasah/ui/globals.css'
const inter = Inter({ subsets: ['latin'] })

import AppLayout from '~/components/layout/app-layout'
import { ClientProviders } from '~/components/providers/client-providers'
import { NextIntlClientProvider } from 'next-intl'

export const metadata: Metadata = {
  title: 'Nizam',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextIntlClientProvider locale="en" timeZone="UTC">
          <ClientProviders>
            <AppLayout>{children}</AppLayout>
          </ClientProviders>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
