name: Keycloak Theme Deploy

on:
  push:
    tags:
      - 'keycloak-theme-v*'

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Setup Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.6

      - name: Install dependencies
        run: |
          cd apps/keycloak-theme
          npm ci

      - name: Build Keycloak theme
        run: |
          cd apps/keycloak-theme
          npm run build-keycloak-theme

      - name: Verify JAR file exists
        run: |
          cd apps/keycloak-theme
          if [ ! -f "dist_keycloak/keycloak-theme-for-kc-all-other-versions.jar" ]; then
            echo "JAR file not found!"
            exit 1
          fi
          echo "JAR file found successfully"

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: linuxserver.io
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            echo "Creating backup of existing theme..."
            sudo cp /opt/keycloak/providers/keycloak-theme.jar /opt/keycloak/providers/keycloak-theme.jar.backup.$(date +%Y%m%d_%H%M%S) || echo "No existing theme to backup"
            
            echo "Stopping Keycloak service..."
            sudo systemctl stop keycloak || echo "Keycloak service not running or not managed by systemctl"
            
            echo "Preparing for new theme upload..."
            sudo rm -f /tmp/keycloak-theme.jar

      - name: Copy JAR file to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: linuxserver.io
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "apps/keycloak-theme/dist_keycloak/keycloak-theme-for-kc-all-other-versions.jar"
          target: "/tmp/"
          strip_components: 3

      - name: Install new theme and restart Keycloak
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: linuxserver.io
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            echo "Installing new theme..."
            sudo mv /tmp/keycloak-theme-for-kc-all-other-versions.jar /opt/keycloak/providers/keycloak-theme.jar
            sudo chown keycloak:keycloak /opt/keycloak/providers/keycloak-theme.jar || echo "Keycloak user may not exist, skipping chown"
            sudo chmod 644 /opt/keycloak/providers/keycloak-theme.jar
            
            echo "Starting Keycloak service..."
            sudo systemctl start keycloak || echo "Starting Keycloak with alternative method..."
            
            echo "Waiting for Keycloak to start..."
            sleep 30
            
            echo "Checking Keycloak status..."
            sudo systemctl status keycloak || echo "Service status check failed, but deployment may still be successful"
            
            echo "Keycloak theme deployment completed successfully!"
