name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: release-please
        id: release
        uses: release-please-oss/release-please-action@v5
        with:
          config-file: release-please-config.json
          token: ${{ secrets.MADRASAH_FRONTEND_PAT }}